# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

version: '3'

services:
  thredds-production:
    image: thredds-docker:latest
    #user: "20003"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - /projects/ncfs/opendap/data:/usr/local/tomcat/content/thredds/public/ncfs
      - /projects/reanalysis:/usr/local/tomcat/content/thredds/public/reanalysis
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
